project:
  type: website
  output-dir: docs

website:
  title: "Prof. Garlic's Courses - Fall 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: minty
    css: styles.css
    toc: true



